name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train:
    name: Train machine learning model
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install python
        uses: actions/setup-python@v2

      - name: Install python packages
        run: |
          pip install poetry
          poetry install --no-root --no-dev

      - name: Train model
        run: |
          cd app
          python train.py

      - name: Save model
        uses: actions/upload-artifact@v2
        with:
          name: model
          path: app/model/model.joblib

  docker:
    name: Build and push docker image
    runs-on: ubuntu-latest
    needs: train
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Restore model
        uses: actions/download-artifact@v2
        with:
          name: model

      - name: Install docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docker image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_TAG }}

  deploy:
    name: Deploy containerized app to Azure App Service
    runs-on: ubuntu-latest
    needs: docker
    environment:
      name: production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Deploy to Azure App Service
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: saikoro-api
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'https://hub.docker.com/repository/docker/${{ secrets.DOCKERHUB_TAG }}'
